# Date and time values
date1 = 1979-05-27
time1 = 07:32:00
time2 = 00:32:00.999999
dt1 = 1979-05-27T07:32:00Z
dt2 = 1979-05-27T00:32:00-07:00
dt3 = 1979-05-27T00:32:00.999999-07:00
dt4 = 1979-05-27 07:32:00Z
