# String types
str1 = "I'm a string."
str2 = "You can \"quote\" me."
str3 = """
Roses are red
Violets are blue"""
str4 = '''I [dw]on't need \d{2} escapes'''
str5 = """Here are two quotation marks: "". """
str6 = '''Here are three quotation marks: '''.'''

# Literal strings
path = 'C:\Users\nodejs\templates'
quoted = 'Tom "Dubs" Preston-Werner'
regex = '<\i\c*\s*>'
