# Numbers
int1 = +99
int2 = 42
int3 = 0
int4 = -17
hex1 = 0xDEADBEEF
oct1 = 0o755
bin1 = 0b11010110
float1 = +1.0
float2 = 3.1415
float3 = -0.01
float4 = 5e+22
float5 = 1e06
float6 = -2E-2
float7 = 6.626e-34
inf1 = inf
inf2 = +inf
inf3 = -inf
nan1 = nan
nan2 = +nan
nan3 = -nan
